development:
  adapter: postgresql
  database: ticket_novo
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: ticket_novo
  username: postgres
  password: postgres

